global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Xunit;
global using FluentAssertions;
global using trit = Ternary.Trit;
global using Ternary;
global using static Ternary.TritValues;